### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by jakebresnehan** [Hurricane86/Moonboard.Android.App#1]
Hey @Hurricane86!

I have been digging around and thinking about creating my own moon training app. 

Do happen to know much about the API? Is it available? If so do you know the endpoint details?

**Comment by Hurricane86** [comment]
Hi @jakebresnehan ,

do you mean how to get data (aka problems) from the official site?
Unfortunately i don't know nothing about their api / backed.

I have created a crawler in node.js that scans the moonboard.com site and save all problem informations to my database.
Let's my know if you need it

**Comment by jakebresnehan** [comment]
> do you mean how to get data (aka problems) from the official site?
Yeah. I had a look around but couldn't find anything.

> I have created a crawler in node.js that scans the moonboard.com site and save all problem informations to my database.
Let's my know if you need it

Oh that would be awesome!!> do you mean how to get data (aka problems) from the official site?
Yeah. I had a look around but couldn't find anything.

> I have created a crawler in node.js that scans the moonboard.com site and save all problem informations to my database.
Let's my know if you need it

Oh that would be awesome!!

**Comment by Hurricane86** [comment]
Attached there is the nodejs script (be sure to run it in a nodejs shell, to create a proper database and to set the right db credential --- line 8-11 of index.js ]

Attached there is a db backup of some problems.
Be warning...the code is not documented :)

`
[moonboard.zip](https://github.com/Hurricane86/Moonboard.Android.App/files/1084134/moonboard.zip)

`

**Comment by jakebresnehan** [comment]
Awesome.

Thanks heaps!

**Comment by jeunelievre** [comment]
Hi @Hurricane86. Do you have backup of old moonboard setup? It's unavailable in off. site's archive for now.

**Comment by Hurricane86** [comment]
see the db here:
https://github.com/Hurricane86/Moonboard.Android.App/blob/master/app/src/main/assets/moonboardDB.sqlite

problems with holdsType=4 & holdsSetup = 1 are new. Others are old problems!
holds are encoded in a byte array... see here to know how to decode it:

https://github.com/Hurricane86/Moonboard.Android.App/blob/master/app/src/main/java/com/gio/martino/moonboard/ProblemBitmap.java#L59

bye


Il 30 lug 2017 11:15 AM, "jeunelievre" <notifications@github.com> ha
scritto:

**Comment by jeunelievre** [comment]
Have found needed setup in old commit of this db and successfully decoded it in readable format. Thanks a lot! I've spent a lot of time trying to find it:)

**Comment by Hurricane86** [comment]
I'm glad that you have done.

good training ;)
